#En este progama mostrare los diferentes tipos de formas que se puede poner la hora y el dia entre otros etc....

import datetime

hoy = datetime.datetime.now()

print(hoy.strftime("\nDia de la semana abreviado: %a \n\n"))
print(hoy.strftime("Dia de la semana completo: %A \n\n"))
print(hoy.strftime("Mes abreviado: %b \n\n"))
print(hoy.strftime("Mes abreviado: %B \n\n"))
print(hoy.strftime("Fecha completa: %c \n\n"))
print(hoy.strftime("Siglo (empieza a contar desde cero): %C \n\n"))
print(hoy.strftime("Dia del mes (01 - 31): %d \n\n"))
print(hoy.strftime("Dia/hora/a\xf1o: %D \n\n"))
print(hoy.strftime("Dia del mes (1 - 31): %e \n\n"))
print(hoy.strftime("A\xf1o en dos digitos: %g \n\n"))
print(hoy.strftime("A\xf1o en cuatro digitos: %G \n\n"))
print(hoy.strftime("Mes abreviado: %h \n\n"))
print(hoy.strftime("Hora (00 - 23): %H \n\n"))
print(hoy.strftime("Hora (01 - 12): %I \n\n"))
print(hoy.strftime("Dia del a\xf1o: %j \n\n"))
print(hoy.strftime("Mes del 01 al 12: %m \n\n"))
print(hoy.strftime("Minuto: %M \n\n"))
print(hoy.strftime("Salto de linea: %n \n\n"))
print(hoy.strftime("AM o PM: %p \n\n"))
print(hoy.strftime("Hora + AM o PM: %r \n\n"))
print(hoy.strftime("Hora y minutos: %R \n\n"))
print(hoy.strftime("Segundos: %S \n\n"))
print(hoy.strftime("Tabulacion: %t \n\n"))
print(hoy.strftime("Hora, minutos y segundos: %T \n\n"))
print(hoy.strftime("Dia de la semana (numero): %u \n\n"))
print(hoy.strftime("Semana del a\xf1o (empieza en domingo): %U \n\n"))
print(hoy.strftime("Semana del a\xf1o(Condiciones especiales): %V \n\n"))
print(hoy.strftime("Semana del a\xf1o (empieza en lunes): %W \n\n"))
print(hoy.strftime("Dia de la semana (empieza en domingo): %w \n\n"))
print(hoy.strftime("Dia/mes/a\xf1o de dos digitos: %x \n\n"))
print(hoy.strftime("Hora/minutos/segundos: %X \n\n"))
print(hoy.strftime("A\xf1o corto: %y \n\n"))
print(hoy.strftime("A\xf1o largo: %Y \n\n"))
